### ISSUE TITLE
QueryDSL Web Example fails when Predicate is null

### ISSUE THREAD

**Issue by totothekiller** [spring-projects/spring-data-examples#309] opened 2017-10-23 10:11 UTC
Start the QueryDSL Web Example : then go the web page and try to go to page n°2.

It will raise a java.lang.IllegalArgumentException: Predicate must not be null!

Predicate is null when no search is done in UserController. I'll propose a PR ASAP.

**Comment by olivergierke** [comment] 2017-10-23 13:32
That's weird as as of Spring Data 2.0 GA there should never be `null` `Predicate` handed into the method due to [this ticket](https://jira.spring.io/browse/DATACMNS-1168) fixed.

**Comment by olivergierke** [comment] 2018-02-22 13:02
Closing because this has been fixed in Spring Data Commons.

**Closed by olivergierke** 2018-02-22 13:02 UTC

**Comment by M0rfic** [comment] 2019-12-06 15:55
@odrotbohm Seems to still be reproducible with v2.2.1. In my case i have accessed http://localhost/service?page=2 and ended up with `Predicate must not be null!`.

Looking at the [QuerydslPredicateBuilder implementation](https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/querydsl/binding/QuerydslPredicateBuilder.java), when the values map is empty, the `BooleanBuilder` is returned [at line 94](https://github.com/spring-projects/spring-data-commons/blob/1c9fa2f365475e378521164b4a6fc58bb2710653/src/main/java/org/springframework/data/querydsl/binding/QuerydslPredicateBuilder.java#L94), but when there are values, even if none of them is usable inside the for, `builder.getValue()` gets returned [at line 121](https://github.com/spring-projects/spring-data-commons/blob/1c9fa2f365475e378521164b4a6fc58bb2710653/src/main/java/org/springframework/data/querydsl/binding/QuerydslPredicateBuilder.java#L121), which evaluates to `null`.

**Comment by toucheqt** [comment] 2019-12-16 12:54
@M0rfic can confirm.
I've just upgraded from Spring Boot 2.1 to 2.2.1 and the same problem appeared.

**Comment by M0rfic** [comment] 2019-12-16 14:01
@toucheqt for the time being, I have worked around it by copying & modifying some of Spring's classes to provide my own predicate builder. For the sake of brevity, you can see below ONLY the relevant changes. Please note that the class names are the original ones prefixed with "My".

Custom `EnableSpringDataWebSupport` annotation to enable support. It imports the original `EnableSpringDataWebSupport.SpringDataWebConfigurationImportSelector` and the custom `MyQuerydslWebConfiguration` via the inner `QuerydslActivator`:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Inherited
@Import({EnableSpringDataWebSupport.SpringDataWebConfigurationImportSelector.class, MyEnableSpringDataWebSupport.QuerydslActivator.class})
public @interface MyEnableSpringDataWebSupport {

    class QuerydslActivator implements ImportSelector {
        @Override
        public String[] selectImports(AnnotationMetadata importingClassMetadata) {
            return QuerydslUtils.QUERY_DSL_PRESENT ? new String[]{MyQuerydslWebConfiguration.class.getName()} : new String[0];
        }
    }
}
```

Custom `QuerydslWebConfiguration` building the custom `QuerydslPredicateArgumentResolver`:
```java
@Configuration
public class MyQuerydslWebConfiguration implements WebMvcConfigurer {
    @Lazy
    @Bean
    public MyQuerydslPredicateArgumentResolver querydslPredicateArgumentResolver() {
        return new MyQuerydslPredicateArgumentResolver(querydslBindingsFactory(), Optional.of(conversionService.getObject()));
    }
}
```

Custom `QuerydslPredicateArgumentResolver` that uses the custom `QuerydslPredicateBuilder`:
```java
public class MyQuerydslPredicateArgumentResolver implements HandlerMethodArgumentResolver {

    private final MyQuerydslPredicateBuilder predicateBuilder;

    public MyQuerydslPredicateArgumentResolver(QuerydslBindingsFactory factory, Optional<ConversionService> conversionService) {
        this.bindingsFactory = factory;
        this.predicateBuilder = new MyQuerydslPredicateBuilder(conversionService.orElseGet(DefaultConversionService::new), factory.getEntityPathResolver());
    }
```

Custom `QuerydslPredicateBuilder` that extends the original one and overrides the `getPredicate` method "wrapping" it with a null check to return an `IncludeAllPredicate` when we end up in this situatiuon (you can also use a `new BooleanBuilder()` like the original does. I derived mine from it because I just wanted more clarity)
```java
public class MyQuerydslPredicateBuilder extends QuerydslPredicateBuilder {

    public MyQuerydslPredicateBuilder(ConversionService conversionService, EntityPathResolver resolver) {
        super(conversionService, resolver);
    }

    @Override
    public Predicate getPredicate(TypeInformation<?> type, MultiValueMap<String, String> values, QuerydslBindings bindings) {
        // if not null, return the predicate generated by the original builder
        return Optional.ofNullable(super.getPredicate(type, values, bindings))
                       // otherwise, return an IncludeAllPredicate predicate that does not filter out anything
                       .orElse(new IncludeAllPredicate());
    }
}
```
