### ISSUE TITLE
Add example for adding custom behaviour to all repositories.

### ISSUE THREAD

**Issue by thomasdarimont** [spring-projects/spring-data-examples#78] opened 2015-04-16 08:06 UTC
We should add an example that demonstrates [this](http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-behaviour-for-all-repositories).

**Comment by olivergierke** [comment] 2015-04-16 09:08
:+1: I'm in the finishing steps for [DATACMNS-542](https://jira.spring.io/browse/DATACMNS-542), which should significantly ease this. There's already a [feature branch](https://github.com/spring-projects/spring-data-jpa/commits/issue/DATACMNS-542) with a pretty complete implementation of this. Feel free to use this to spike an example.

**Comment by olivergierke** [comment] 2015-04-16 09:58
Trying to find the missing test cases for the JPA feature branch I discovered that there's a branch here to solve #73, which is basically a duplicate of this one. I'll reopen it as it apparently hasn't been merged into master yet (pending completion of the improvements in Spring Data Commons / JPA).

**Comment by thomasdarimont** [comment] 2015-04-16 10:14
Alright :)

**Comment by mp911de** [comment] 2023-04-24 11:44
Fixed via [b8e2943](https://github.com/spring-projects/spring-data-examples/commit/b8e29431de793b8a2234e193ac68d7956c300969)

**Closed** 2023-04-24 11:44 UTC
Labels: status: waiting-for-triage
